### PR TITLE
updated session bug to include a new dojo module for creating generic…

### LINKED ISSUE #31: Refactor form.js to be a dojo module
- [ ] Make it a dojo module for use in history-widget
- [ ] Make sure it works with index.html
- [ ] Make usre it works with authordemo.html

### PR DESCRIPTION
**Pull request by riteshsamala**
… form

fixes #31

### CODE REVIEW

**Comment by jonwetzel** [comment]
@riteshsamala Merge conflict detected.

**Comment by riteshsamala** [comment]
Fixed the merge conflict

File: www/js/history-widget.js [hunk 1]
```diff
@@ -117,38 +117,47 @@ define([
...
+					type: "text",
+					value: query_params[prop]
+				})
+			}
+			if(!session_element_exists){
+				elements_data.push({
+					name: "x",
+					type: "text",
+					value: ""
+				})
```
Comment (sachingrover211) [inline www/js/history-widget.js]: we should follow one rule, whether to put semi colon at the end or not. I think since we are putting it would it be possible to just to stick to that, just to maintain uniformity.

File: www/js/history-widget.js [hunk 2]
```diff
@@ -117,38 +117,47 @@ define([
...
-			else{
-				form.x.value = session_id;
-			}
-			submit();		
+			console.log("session_id",session_id);
+			//history_form has already been created and attached in initial handlers
+			var form = document.forms["history_form"];
+			//update the session id parameter based on the particular session in history
+			//to be loaded identified by session_id
+			form.x.value = session_id;
```
Comment (sachingrover211) [inline www/js/history-widget.js]: are we sure that form.x will always be there?

File: www/js/history-widget.js (hunk 1 above)
Comment (sachingrover211) [inline www/js/history-widget.js]: this would send empty session value. Is it an expected behavior?

File: www/js/history-widget.js (hunk 2 above)
Comment (riteshsamala) [inline www/js/history-widget.js]: yes, for all the sessions which is not current session, button will have a handler attached to it (we push "x" element each time and fill its value with session id the entry corresponds to, this also answers the third comment).

File: www/js/history-widget.js (hunk 1 above)
Comment (riteshsamala) [inline www/js/history-widget.js]: sure

Comment (sachingrover211) [inline www/js/history-widget.js]: @riteshsamala what about this comment?

Comment (riteshsamala) [inline www/js/history-widget.js]: discusses this with you already, refer first comment

Comment (riteshsamala) [inline www/js/history-widget.js]: updated
